### ISSUE TITLE
From Scott on Gitter

### ISSUE THREAD

**Issue by TC2013** [scottleibrand/openaps-sh#2]
openaps alias add loop '! bash -c "openaps preflight && openaps gather && openaps get-settings >/dev/null && openaps enact; openaps upload"' works, but openaps alias add loop '! bash -c "openaps preflight && openaps gather && openaps get-settings >/dev/null && openaps enact ; openaps upload"' doesn't. difference is the space before the ;

Line 144

**Comment by TC2013** [comment]
I see you already fixed it in dev.

**Comment by scottleibrand** [comment]
Yeah, I have a habit of fixing things in that repo locally and not pushing. Will have to be better about that now. :-)

**Comment by TC2013** [comment]
This weekend I went through I combined meal-assist-setup.sh and the main setup.sh… very proud of myself.  I go to your site to submit it and I see you already did it!  

:)  It was a good exercise!
